# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Workflow Demo

on: [push]

jobs:
  ExecutePython:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Version
        run: python -V
      - name: Identifying the Folder
        run: pwd
      - name: List the files in current directory
        run: ls ${{github.workspace}}
      - name: Run Python File
        run: python ../devsecops-cgi/hello.py
